### ISSUE TITLE
First run gives 'System.InvalidOperationException' occurred in Murder.dll: 'Unable to find preload content.'

### ISSUE THREAD

**Issue by pieandcakes** [isadorasophia/hellomurder#9]
I came to check this out but I can't figure out how to get preload_data.gz to generate.

1. Cloned repo
2. git submodule update --init --recursive
3. dotnet restore hellomurder.sln
4. dotnet build
5. F5 in VSCode

Program stops at: 

GameDataManager.cs line 274:

Exception has occurred: CLR/System.InvalidOperationException
An unhandled exception of type 'System.InvalidOperationException' occurred in Murder.dll: 'Unable to find preload content.'
   at Murder.Data.GameDataManager.PreloadContentImpl() in c:\src\hellomurder\murder\src\Murder\Data\GameDataManager.cs:line 274
   at Murder.Data.GameDataManager.PreloadContent() in c:\src\hellomurder\murder\src\Murder\Data\GameDataManager.cs:line 233
   at Murder.Data.GameDataManager.LoadContent() in c:\src\hellomurder\murder\src\Murder\Data\GameDataManager.cs:line 225
   at Murder.Game.LoadContent() in c:\src\hellomurder\murder\src\Murder\Game.cs:line 481
   at Microsoft.Xna.Framework.Game.Initialize()
   at Murder.Game.Initialize() in c:\src\hellomurder\murder\src\Murder\Game.cs:line 390
   at Microsoft.Xna.Framework.Game.DoInitialize()
   at Microsoft.Xna.Framework.Game.Run()
   at HelloMurder.Program.Main() in c:\src\hellomurder\src\HelloMurder\Program.cs:line 14

**Comment by pieandcakes** [comment]
Never mind. its because i misread and was F5ing the Solution and not the HelloMurder.Editor project only.
